name: Link HTML files
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: extractions/setup-just@v2
            - run: just lint-html
